version: '3'

services:
  php:
    container_name: stc_othello_php
    build: ./docker/php
    volumes:
    - ./dist:/var/www

  nginx:
    image: nginx
    container_name: stc_othello_nginx
    ports:
    - 28888:80
    volumes:
    - ./dist:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: stc_othello_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 23306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: stc_othello_phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: docker
      PMA_PASSWORD: docker
    restart: always
    links:
      - db:mysql
    ports:
      - 28889:80
  